### ISSUE TITLE
Do your best

### ISSUE THREAD

**Issue by rentacka** [tsuggate/Typifier#1]
Typescript code can not be passed to Developer Tool. Therefore, it is impossible to specify the error position.

Keep in Javascript what you can not convert. Please show me that you can not convert on it.

I hope we can do better things.

**Comment by tsuggate** [comment]
If I understand correctly, you have some Javascript code that is failing to be converted, and you aren't getting a message about what line it's failing on?

If you can give me the error message you are getting and/or some code that reproduces the error that would be very helpful.
